log_level = "debug"
host = "0.0.0.0"
port = 3000
mnemonic = "equal dragon fabric refuse stable cherry smoke allow alley easy never medal attend together lumber movie what sad siege weather matrix buffalo state shoot"

default_relay = "ws://localhost:7010"

[register]
# rpc endpoint
endpoint = "https://1rpc.io/holesky"
# operator register contract address
contract = "0x27e4384ecc11810c2F49914390052b22c4e3CcC0"

account = "equal dragon fabric refuse stable cherry smoke allow alley easy never medal attend together lumber movie what sad siege weather matrix buffalo state shoot"