
[log]
# log level
level="debug"


[nostr]
# nostr relay
relay="ws://localhost:7010"


[server]
# server config
host = "0.0.0.0"
port = 3000


[db]
# postgres database url
url="postgres://postgres:hetuproject@postgres:5432/postgres"


[account]
# the account mnemonic of the dispatcher to send message to operator
mnemonic = ""


[register]
# register contract chain rpc endpoint
endpoint = "https://1rpc.io/holesky"
# operator register contract address
contract = "0x0C6425A2C1548a69729a491533FF882bd8de5752"
# the account mnemonic of the register contract owner
account = ""


[admin]
# the verify token of admin
token = ""